### ISSUE TITLE
MIPSEL static compilation issues

### ISSUE THREAD

**Issue by jassycliq** [angelcam/arrow-client#40]
Thanks for this wonderful project!
I've been trying to get the arrow client compiled for the Wyze cam v2 which runs an Ingenic T20 (mipsel based) chipset. Unfortunately, the only toolchain that I could find for it is an uclibc toolchain which required me to go the static build route.

After much trial and error I was finally able to get it to successfully compile by adding the following lines to the static-build bash script:

`rustflags = ["-C", "target-feature=+crt-static", "-C", "link-args=-lgcc"]`

I've been running this for a few hours without issue but was wondering if if this would cause any issues further down the road or if there is a way to build without this workaround.

**Comment by operutka** [comment]
Hi @jassycliq! Thank you for your interest in this project.

The script for static linking with MUSL is there mostly as an example. uClibc targets are quite problematic and different GCC toolchains may require different compilation options. Those options that you mentioned should be fine. They affect linking and if you managed to link the resulting binary successfully, it should work fine.

I should also mention that `mipsel-unknown-linux-uclibc` is currently supported by Rust as a Tier 3 target. It means that it should be possible to build Arrow Client without linking it statically to MUSL. You'll need Rust nightly though and you'll also need to use the "build-std" feature of Cargo:
https://doc.rust-lang.org/cargo/reference/unstable.html#build-std

It should be relatively simple. You'll need to create a `.cargo/config` like this:
```toml
# uncomment these if some crates fail to compile because of missing std
# [build]
# rustflags = ["--cfg=has_std"]

[unstable]
build-std = ["core", "std", "alloc", "proc_macro", "panic_abort", "panic_unwind"]
build-std-features = []
# if there are problems with missing symbols for the backtrace-rs, you can try these two instead:
# build-std = ["core", "std", "alloc", "proc_macro", "panic_abort"]
# build-std-features = ["panic_immediate_abort"]

[target.mipsel-unknown-linux-uclibc]
# adjust these two according to your cross toolchain
ar = "mipsel-openwrt-linux-uclibc-ar"
linker = "mipsel-openwrt-linux-uclibc-gcc"
```

You'll also need to add path to your cross toolchain bin to the `PATH` env. variable. And you'll also need to set `CC_mipsel_unknown_linux_uclibc` to the name of your cross GCC bin.

Once you've set up all this you can just build Arrow Client using:
```bash
cargo +nightly build --target=mipsel-unknown-linux-uclibc --release --verbose
```
